# Script for Azure Pipelines
# https://docs.microsoft.com/azure/devops/pipelines

pool:
  vmImage: $(vmImage)

steps:
- script: |
    echo my vmImage is $(vmImage)

- task: UseDotNet@2
  inputs:
    packageType: 'sdk' # Options: runtime, sdk
    version: '3.1.100' 

- script: dotnet --version

- task: NugetToolInstaller@1
- task: DotNetCoreCLI@2
  inputs:
    command: restore
    projects: '{your project}'

- task: DotNetCoreCLI@2
  displayName: 'test'
  inputs:
    command: test
    projects: |
      **/PersistentProcess.Test.csproj
    arguments:  --logger trx
    publishTestResults: false

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'

- script: dotnet publish ./implement/elm-fullstack/elm-fullstack.csproj
  displayName: 'publish web host'
