name: test-and-publish

on: [push]

jobs:
  build:

    strategy:
      matrix:
        environment: [ubuntu-18.04,windows-2019]

    runs-on: ${{ matrix.environment }}

    steps:
    - uses: actions/setup-dotnet@v1.2.0
      with:
        dotnet-version: '3.1.100'
    - name: Try use dotnet core 3
      run: dotnet --info
    - uses: actions/checkout@v1
    - name: Run tests
      run: dotnet test ./implement/PersistentProcess/PersistentProcess.Test/PersistentProcess.Test.csproj --logger trx
    - name: dotnet publish
      run: dotnet publish -c Debug ./implement/elm-fullstack

    - name: Create commit comment
      uses: peter-evans/commit-comment@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          This is a multi-line test comment
          - With GitHub **Markdown**
          - Created by [commit-comment][1]

          [1]: https://github.com/peter-evans/commit-comment

    - name: Publish artifacts
      uses: actions/upload-artifact@v1
      with:
        name: executable-files-${{github.sha}}-${{ matrix.environment }}
        path: ./implement/elm-fullstack/bin/Debug/netcoreapp3.1/publish
